    Topics:
    
    1. Understanding Semantic Word Vectors
    2. Understanding Sentiment Analysis
    3. Leverage Sentiment Analysis for Text Classification
    
https://spacy.io/usage/models

At the command line, download the medium or large spacy english models:

    > python -m spacy download en_core_web_md
    > python -m spacy download en_core_web_lg
    

If we don't specify _md or _lg, by default it small word vectors.

Pretrained word vectors

    1. Word2Vec
        - It is a two-layer neural net that processes text.
        - Input = Text Corpus
        - Output = Set of Vectors: feature vectors for words in that corpus
        - It is useful group the vectors of similar words together in vector space.
        - It detects similarities mathematically
        - It establishes the word's association with other words (e.g. 'man' is to 'boy' and 'woman' is to 'girl')
        
    

It trains words against the other words that neighbor them in the input corpus. It does in 2 ways.
    1. Either using context to prdict a target word ( using CBOW: Continuous Bag of Words method)
    2. or Word to predict a target context (Skip-Gram Method)

    Recall:
    
        1. Each word is now represented by a vector
        2. In spacy each of these vectors has 300 dimensions    

## Word Vectors with Spacy

In [1]:
import spacy

In [5]:
nlp = spacy.load('en_core_web_md')

Medium is already installed hence successul, install large in anacond prompt using the above command.

In [7]:
nlp(u'lion').vector

array([ 1.8963e-01, -4.0309e-01,  3.5350e-01, -4.7907e-01, -4.3311e-01,
        2.3857e-01,  2.6962e-01,  6.4332e-02,  3.0767e-01,  1.3712e+00,
       -3.7582e-01, -2.2713e-01, -3.5657e-01, -2.5355e-01,  1.7543e-02,
        3.3962e-01,  7.4723e-02,  5.1226e-01, -3.9759e-01,  5.1333e-03,
       -3.0929e-01,  4.8911e-02, -1.8610e-01, -4.1702e-01, -8.1639e-01,
       -1.6908e-01, -2.6246e-01, -1.5983e-02,  1.2479e-01, -3.7276e-02,
       -5.7125e-01, -1.6296e-01,  1.2376e-01, -5.5464e-02,  1.3244e-01,
        2.7519e-02,  1.2592e-01, -3.2722e-01, -4.9165e-01, -3.5559e-01,
       -3.0630e-01,  6.1185e-02, -1.6932e-01, -6.2405e-02,  6.5763e-01,
       -2.7925e-01, -3.0450e-03, -2.2400e-02, -2.8015e-01, -2.1975e-01,
       -4.3188e-01,  3.9864e-02, -2.2102e-01, -4.2693e-02,  5.2748e-02,
        2.8726e-01,  1.2315e-01, -2.8662e-02,  7.8294e-02,  4.6754e-01,
       -2.4589e-01, -1.1064e-01,  7.2250e-02, -9.4980e-02, -2.7548e-01,
       -5.4097e-01,  1.2823e-01, -8.2408e-02,  3.1035e-01, -6.33

In [8]:
nlp(u'lion').vector.shape # It is a numpy array

(300,)

In [10]:
nlp(u'fox').vector.shape

(300,)

In [9]:
nlp(u'The quick brown fox jumped').vector

array([-2.09217995e-01, -2.78227981e-02, -3.57064009e-02,  1.55218393e-01,
       -1.28050027e-02,  1.31627038e-01, -1.99465990e-01,  4.75811996e-02,
        1.26798794e-01,  1.64792800e+00, -3.57592016e-01, -1.39875397e-01,
       -1.26122087e-02, -2.02728346e-01, -2.25237608e-01,  2.15431936e-02,
        7.78958052e-02,  9.29676056e-01, -2.75549982e-02, -3.71005982e-01,
       -1.42800003e-01, -3.66641544e-02, -1.07376035e-02, -1.84352830e-01,
        2.29006782e-02, -5.17717972e-02, -2.78652012e-01, -1.19738199e-01,
        5.10960072e-03, -2.85990000e-01, -1.58261746e-01,  2.96241999e-01,
        1.09597601e-01, -4.18331996e-02,  1.87256075e-02, -1.03439607e-01,
       -5.10879979e-02, -3.51091917e-03, -6.81461841e-02, -2.05657601e-01,
        1.66347414e-01, -9.31599736e-03, -4.61134054e-02, -1.05457589e-01,
        2.31313989e-01,  1.80005193e-01, -2.06444815e-01, -1.37050152e-02,
        1.70106202e-01, -2.19812002e-02, -2.14003205e-01,  1.07415602e-01,
       -2.80592032e-02, -

In [11]:
tokens = nlp('lion cat pet')

In [12]:
tokens

lion cat pet

In [13]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.52654374
lion pet 0.39923766
cat lion 0.52654374
cat cat 1.0
cat pet 0.7505456
pet lion 0.39923766
pet cat 0.7505456
pet pet 1.0


We can clearly see the Words Vectors with Similarity.

In [14]:
tokens = nlp('like love hate')

In [15]:
for token1 in tokens:
    for token2 in tokens:
        print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love 0.65790397
like hate 0.6574652
love like 0.65790397
love love 1.0
love hate 0.6393099
hate like 0.6574652
hate love 0.6393099
hate hate 1.0


Similar words will have similar vectors with high cosine similarity. In English, love and hate are opposite but if you see it has high similarity.

In [16]:
len(nlp.vocab.vectors)

20000

In [2]:
nlp = spacy.load('en_core_web_lg')

In [3]:
len(nlp.vocab.vectors)

684831

It means this has 684831 unique word vectors

In [4]:
nlp.vocab.vectors.shape

(684831, 300)

In [5]:
tokens = nlp(u"dog cat nargle")

In [6]:
for token in tokens:
    print(token.text,token.has_vector,token.vector_norm,token.is_oov) # vector_norm = normalized vector, is_oov = is out of vocabulary

dog True 7.0336733 False
cat True 6.6808186 False
nargle False 0.0 True


In [7]:
from scipy import spatial

cosine_similarity = lambda vec1, vec2: 1 - spatial.distance.cosine(vec1,vec2)

In [8]:
cosine_similarity

<function __main__.<lambda>(vec1, vec2)>

In [9]:
king = nlp.vocab['king'].vector
man = nlp.vocab['man'].vector
woman = nlp.vocab['woman'].vector

In [10]:
# king - man + woman   ---> New Vector similar to Queen, princess, highness

In [11]:
new_vector = king-man+woman

In [13]:
computed_similarities = []

# FOR ALL WORDS (684831) IN VOCAB

for word in nlp.vocab:
    if word.has_vector:
        if word.is_lower:
            if word.is_alpha:
                similarity = cosine_similarity(new_vector,word.vector)
                computed_similarities.append((word,similarity))

In [14]:
computed_similarities = sorted(computed_similarities,key = lambda item:-item[1]) # lambda item:-item[1], gives descending order

In [15]:
print([t[0].text for t in computed_similarities[:10]])

['king', 'queen', 'prince', 'kings', 'princess', 'royal', 'throne', 'queens', 'monarch', 'kingdom']


In [20]:
print([t[0].text for t in computed_similarities[:10]])

['king', 'queen', 'prince', 'kings', 'princess', 'royal', 'throne', 'queens', 'monarch', 'kingdom']


## Sentiment Analysis

** VADER Sentiment with NLTK**

- VADER (Valence Aware Dictionary for SEntiment Reasoning) is a model used for text sentiment analysis that is senstive to both polarity (Positive/Negative) and intensity (strength) of emotion)
    
- It is available in the NLTK package and can be directly applied to unlabelled text data.
    
- VADER Sentiment analysis relies on a dictionary which maps lexical features to emotion intensities called sentiment score
    
- The Sentiment score of a text can be obtained by summing up the intensity of each word in the text. 
    
- Note that every single word has some sort of positive or negative value attached to it
    
E.g. 
 
- words like "love", "like","happy","enjoy" all convey a positive sentiment
- VADER is intelligent enough to understand basic context like "did not love" as negative sentiment
- It also understands capitalization and punctuation such as "Love!!!" 

Sentiment Analysis on raw text is always challenging however due to variety of possible factors 

- Positive and Negative Sentiment in the same text data
- Sarcasm using positive words in a negative way

In [1]:
import nltk

In [2]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\chalampp\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [3]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [4]:
sid = SentimentIntensityAnalyzer()

In [5]:
a = "This is a good movie"

sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [6]:
a = "This was the best, most awesome movie EVER MADE!!!"

sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [7]:
a = "This was Worst Movie that has ever disgraced the screen"

sid.polarity_scores(a)

{'neg': 0.47, 'neu': 0.53, 'pos': 0.0, 'compound': -0.7964}

A compound score above zero indicates some sort of positive score and then a compound score below zero indicates some sort of negative score.

In [8]:
# Reviews Amazon text

import pandas as pd

df = pd.read_csv("amazonreviews.tsv",sep ='\t')

In [9]:
df.head(5)

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [10]:
df.shape

(10000, 2)

In [11]:
df.label.unique()

array(['pos', 'neg'], dtype=object)

In [12]:
df.label.value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [13]:
df.dropna(inplace = True)

In [14]:
blanks = []

for i,lb,rv in df.itertuples():
    # index, label, review
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [15]:
blanks

[]

In [16]:
# df.drop(blanks,inplace = True) # This is not something clear from video

In [17]:
df.iloc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [18]:
df.head(1)

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...

In [19]:
sid.polarity_scores(df.iloc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [20]:
df['scores'] = df['review'].apply(lambda review:sid.polarity_scores(review))

In [21]:
df.head(5)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [22]:
# add the above syntax to ML Index Preprocessing and put in Github

In [24]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [25]:
df.head(5)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781

If Compound Score is greater than Zero, it is Positive. Otherwwise it is negative.

In [26]:
df['comp_score'] = df['compound'].apply(lambda score: 'pos' if score >=0 else 'neg')

In [27]:
df.head(5)

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  compound comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...    0.9454        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...    0.8957        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...    0.9858        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...    0.9814        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...    0.9781        pos

In [28]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [29]:
accuracy_score(df['label'], df['comp_score'])

0.7091

In [31]:
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.51      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



In [32]:
print(confusion_matrix(df['label'], df['comp_score']))

[[2623 2474]
 [ 435 4468]]


## Movie Review Project

In [33]:
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('moviereviews.tsv',sep='\t')

In [36]:
df.head(5)

label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [37]:
df.dropna(inplace = True)

In [38]:
blanks =[]

for i,lb,rv in df.itertuples():
    # index, label, review
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [40]:
print(blanks)

[57, 71, 147, 151, 283, 307, 313, 323, 343, 351, 427, 501, 633, 675, 815, 851, 977, 1079, 1299, 1455, 1493, 1525, 1531, 1763, 1851, 1905, 1993]


In [41]:
df.drop(blanks,inplace= True) 

In [42]:
print(blanks)

[57, 71, 147, 151, 283, 307, 313, 323, 343, 351, 427, 501, 633, 675, 815, 851, 977, 1079, 1299, 1455, 1493, 1525, 1531, 1763, 1851, 1905, 1993]


In [44]:
df['label'].value_counts()

pos    969
neg    969
Name: label, dtype: int64

In [45]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [46]:
sid = SentimentIntensityAnalyzer()

In [48]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))

In [50]:
df.head(5)

label                                             review  \
0   neg  how do films like mouse hunt get into theatres...   
1   neg  some talented actresses are blessed with a dem...   
2   pos  this has been an extraordinary year for austra...   
3   pos  according to hollywood movies made in last few...   
4   neg  my first press screening of 1998 and already i...   

                                              scores  
0  {'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...  
1  {'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...  
2  {'neg': 0.067, 'neu': 0.783, 'pos': 0.15, 'com...  
3  {'neg': 0.069, 'neu': 0.786, 'pos': 0.145, 'co...  
4  {'neg': 0.09, 'neu': 0.822, 'pos': 0.088, 'com...

In [52]:
print(df[['scores']])

                                                 scores
0     {'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...
1     {'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...
2     {'neg': 0.067, 'neu': 0.783, 'pos': 0.15, 'com...
3     {'neg': 0.069, 'neu': 0.786, 'pos': 0.145, 'co...
4     {'neg': 0.09, 'neu': 0.822, 'pos': 0.088, 'com...
...                                                 ...
1995  {'neg': 0.073, 'neu': 0.764, 'pos': 0.163, 'co...
1996  {'neg': 0.237, 'neu': 0.689, 'pos': 0.074, 'co...
1997  {'neg': 0.15, 'neu': 0.705, 'pos': 0.145, 'com...
1998  {'neg': 0.129, 'neu': 0.711, 'pos': 0.16, 'com...
1999  {'neg': 0.071, 'neu': 0.741, 'pos': 0.188, 'co...

[1938 rows x 1 columns]


In [53]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [54]:
df['comp_score'] = df['compound'].apply(lambda score: 'pos' if score >=0 else 'neg')

In [55]:
df.head(5)

label                                             review  \
0   neg  how do films like mouse hunt get into theatres...   
1   neg  some talented actresses are blessed with a dem...   
2   pos  this has been an extraordinary year for austra...   
3   pos  according to hollywood movies made in last few...   
4   neg  my first press screening of 1998 and already i...   

                                              scores  compound comp_score  
0  {'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...   -0.9125        neg  
1  {'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...   -0.8618        neg  
2  {'neg': 0.067, 'neu': 0.783, 'pos': 0.15, 'com...    0.9953        pos  
3  {'neg': 0.069, 'neu': 0.786, 'pos': 0.145, 'co...    0.9972        pos  
4  {'neg': 0.09, 'neu': 0.822, 'pos': 0.088, 'com...   -0.7264        neg

In [56]:
accuracy_score(df['label'], df['comp_score'])

0.6367389060887513

In [57]:
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

    accuracy                           0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938



In [58]:
print(confusion_matrix(df['label'], df['comp_score']))

[[427 542]
 [162 807]]


## Sentiment Analysis Assessment

### Task 1: Perform Vector Arithmetic on your own words

Goal: Come as close to an expected word as possible

In [60]:
# Import Spacy and load the large language library

import spacy
nlp = spacy.load('en_core_web_lg')

In [62]:
# Choose the words you wish to compare and obtain their vectors

word1 = nlp.vocab['wolf'].vector
word2 = nlp.vocab['dog'].vector
word3 = nlp.vocab['cat'].vector

In [63]:
# Import spatial and define a cosine_similarity function

from scipy import spatial

cosine_sim = lambda x,y: 1 - spatial.distance.cosine(x,y)

In [64]:
# Write an expression for vector arithmetic
# for example, new vector = word1-word2+word3

new_vector = word1-word2+word3

In [65]:
new_vector

array([-3.31050038e-01, -7.70348012e-01, -1.61958992e-01,  5.14509976e-02,
       -4.39818025e-01,  5.61370015e-01, -7.02800155e-02, -1.59049034e-02,
       -3.21312010e-01,  3.47299814e-01, -4.55450028e-01, -8.28244984e-01,
       -7.40220010e-01, -5.42928994e-01, -5.63299805e-02,  4.28279996e-01,
       -4.62331504e-01,  4.05170023e-01, -5.48449993e-01,  1.02373034e-01,
        1.80074990e-01, -7.66499713e-03, -2.12929994e-01, -2.46849999e-01,
       -5.52890062e-01,  9.38629806e-02, -7.23510027e-01,  7.02539980e-02,
        5.78920245e-02,  1.84492990e-01, -4.80529994e-01,  2.75459979e-02,
        6.71660006e-02, -5.13229966e-01,  2.37689972e-01, -3.08634996e-01,
        3.63579988e-01, -1.35779977e-01, -7.75561988e-01, -4.09240007e-01,
       -3.27869982e-01,  3.85720015e-01,  3.15609947e-02, -1.71799973e-01,
        6.24130011e-01,  2.73019969e-02, -2.17069983e-01,  3.58170003e-01,
       -6.13200068e-02, -3.95631999e-01, -1.76720008e-01, -1.14570022e-01,
       -6.55736983e-01, -

In [66]:
new_vector.shape

(300,)

In [67]:
# List the top ten closest vectors in the vocabulary to the result of the

computed_sims = []

for word in nlp.vocab:
    if word.has_vector:
        if word.is_lower:
            if word.is_alpha:
                sim = cosine_sim(new_vector,word.vector)
                computed_sims.append((word,sim)) 

In [69]:
computed_sims[:2]

[(<spacy.lexeme.Lexeme at 0x1f4adfed188>, -0.008464708924293518),
 (<spacy.lexeme.Lexeme at 0x1f4adfed458>, 0.07630855590105057)]

In [71]:
computed_sims = sorted(computed_sims,key = lambda item: -item[1])

In [72]:
[w[0].text for w in computed_sims[:10]]

['wolf',
 'wolves',
 'panther',
 'lynx',
 'owl',
 'tiger',
 'lion',
 'fox',
 'cat',
 'otter']

### Challeng: Write a function that takes in 3 strings, perform a-b+c arithmetic, and returns a top ten result

In [83]:
def vector_math(a,b,c):
    
    word1 = nlp.vocab[a].vector
    word2 = nlp.vocab[b].vector
    word3 = nlp.vocab[c].vector
    
    new_vector = word1 - word2 + word3
    
    computed_sims = []

    for word in nlp.vocab:
        if word.has_vector:
            if word.is_lower:
                if word.is_alpha:
                    sim = cosine_sim(new_vector,word.vector)
                    computed_sims.append((word,sim)) 
    
    computed_sims = sorted(computed_sims,key = lambda item: -item[1])
    
    return [w[0].text for w in computed_sims[:10]]

In [84]:
# The above function is best example how to build

In [85]:
# Test the function on known words

print(vector_math('king','man','woman'))

['king', 'queen', 'prince', 'kings', 'princess', 'royal', 'throne', 'queens', 'monarch', 'kingdom']


In [86]:
print(vector_math('wolf','dog','cat'))

['wolf', 'wolves', 'panther', 'lynx', 'owl', 'tiger', 'lion', 'fox', 'cat', 'otter']


### Task 2: Perform VADER Sentiment Analysis on your own review

**Write Code that returns a set of SentimentintensityAnalyzer polarity scores based on your own written review**

In [87]:
# Import Sentiment Intensity Analyzer and create an sid object

from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [88]:
# Write a review as one continuous string (multiple sentences are ok)

review = 'This moview was absolutely awful. The WORST Movie I have ever seen!!!'

In [89]:
# obtain the sid scores for your review

sid.polarity_scores(review)

{'neg': 0.507, 'neu': 0.493, 'pos': 0.0, 'compound': -0.8825}

### Challeng: Write a function that takes in a review and returns a score of "Positive", "Negative", or "Neutral"

In [92]:
def review_rating(string):
    scores = sid.polarity_scores(string)
    
    if scores['compound'] == 0:
        return "Neutral"
    
    elif scores['compound'] > 0:
        return "Positive"
    
    else:
        return "Negative"

In [93]:
review_rating(review)

'Negative'